### ISSUE TITLE
pyroute2 0.7.1

### ISSUE THREAD

**Issue by frenck** [bdraco/unifi-discovery#24]
Got a dependency conflict @ Home Assistant

![image](https://user-images.githubusercontent.com/195327/178942918-21db432b-955f-468e-856c-b76ac55c9867.png)

Caused by the release of pyroute2 0.7.1

![image](https://user-images.githubusercontent.com/195327/178942985-24673e46-caea-4436-9f1d-dbbb2e5fe265.png)

Which originates from this repository

**Comment by bdraco** [comment]
Will publish a new one later today

**Comment by frenck** [comment]
No rush 👍

**Comment by bdraco** [comment]
Published 1.1.5

Need to wait for https://github.com/home-assistant/core/pull/75180 to bump it
